[package]
name = "ruff"
version = "0.2.0"
edition = "2021"
authors = ["Robert DeVore <me@robertdevore.com>"]
description = "Ruff â€” A lean, expressive programming language"
license = "MIT"
readme = "README.md"
repository = "https://github.com/rufflang/ruff"

[dependencies]
clap = { version = "4", features = ["derive"] }
once_cell = "1.21.3"
colored = "2.1"
serde_json = "1.0"
